SYSTEM_NAME="apple2"
SYSTEM_FULLNAME="Apple II"
SYSTEM_MANUFACTURER="Apple"
SYSTEM_RELEASE="1977"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/apple2"
SYSTEM_EXTENSION=".dsk .do .po .nib .woz .2mg .hdv .zip .7z"
SYSTEM_PLATFORM="apple2"
SYSTEM_THEME="apple2"
SYSTEM_WIKI_PATH="apple2"
